### ISSUE TITLE
Suggestion : url

### ISSUE THREAD

**Issue by Arth-kun** [Hatisoft/PlayYouTube#13]
It could be nice if we could provide it a playlist or video url directly in the search file, don't know if it's a lot of code for you or not, it could be nice to listen to our personal playlists easily.

Otherwise it's a really great plugin !
Have a nice day :)

**Comment by Arth-kun** [comment]
I want to precise that I'm using the Atom's plugin, not the visual studio's one

**Comment by alvarolorentedev** [comment]
🙏 Sorry For the late reply, I did not get the notification so have not seen this issue 🙏

 moving this to the correct repo https://github.com/kanekotic/playyoutube-atom/issues/20
